Feature branch
somoye123/New-York-Times-Article-Page pull request #1
Opened 2020-06-09 14:08 UTC by Abidoyinsola1

A clone of The New York Times Article Page.

2020-06-09 16:41 UTC, tirthajyoti-ghosh commented
# Pull Request under review by T. Ghosh (TSE)

2020-06-09 16:48 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Impressive project team ✨

But there are couple of issues that still needed to be addressed before you can merge. Check the comments below for more details.

2020-06-09 16:52 UTC, tirthajyoti-ghosh commented on index.html
> +      <img src="./assets/images/NewYork.PNG" alt="The New YorK Times" />
- The NY Times logo must be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2020-06-09 16:55 UTC, tirthajyoti-ghosh commented on index.html
> +    </nav>
- The `nav` element shrinks when the height is changed.
![Annotation 2020-06-09 103602](https://user-images.githubusercontent.com/57726348/84177044-ee22c700-aa9f-11ea-95d0-bc37e3b1f02f.jpg)

2020-06-09 16:57 UTC, tirthajyoti-ghosh commented on index.html
> +      </div>
- The styles are different than the original.
  Original 👇  
  ![Annotation 2020-06-09 222448](https://user-images.githubusercontent.com/57726348/84177246-3b9f3400-aaa0-11ea-8b90-d61553e12eca.jpg)

  Right now 👇  
  ![Annotation 2020-06-09 222437](https://user-images.githubusercontent.com/57726348/84177294-4c4faa00-aaa0-11ea-8937-37ed87a029c1.jpg)

2020-06-09 17:01 UTC, tirthajyoti-ghosh commented on index.html
> +          <div class="main-paragraph">
- The `main-paragraph` must be centered.
  
  Original 👇  
  ![Annotation 2020-06-09 222838](https://user-images.githubusercontent.com/57726348/84177682-d0a22d00-aaa0-11ea-9932-01f20eee7ebc.jpg)

  Right now 👇  
  ![Annotation 2020-06-09 222810](https://user-images.githubusercontent.com/57726348/84177712-e152a300-aaa0-11ea-9ba7-33e7ae7e9f71.jpg)

2020-06-09 17:06 UTC, tirthajyoti-ghosh commented on index.html
> +          <aside>
- Reduce the size of images and texts to match the original and shift the `aside` tag to the right.
  
  Original 👇
  
  ![Annotation 2020-06-09 223329](https://user-images.githubusercontent.com/57726348/84178037-6d64ca80-aaa1-11ea-9cbd-305df88b9c0f.jpg)

  Right now 👇
  
  ![Annotation 2020-06-09 223308](https://user-images.githubusercontent.com/57726348/84178126-8ff6e380-aaa1-11ea-990d-a903d5519e27.jpg)

2020-06-09 17:08 UTC, tirthajyoti-ghosh commented on index.html
> +          </ul>
- The icons must be links.

2020-06-09 17:11 UTC, tirthajyoti-ghosh commented on index.html
> +          <div class="rec-editor-pick">
- Add some space below this `rec-editor-picks`. Right now it's sticking to the `footer`.  
  
  ![Annotation 2020-06-09 224045](https://user-images.githubusercontent.com/57726348/84178582-4955b900-aaa2-11ea-9960-590747bc25a1.jpg)

2020-06-09 17:13 UTC, tirthajyoti-ghosh commented on index.html
> +      <div class="expand">
- Align `expand` with the other elements. Right now it has extra space on top.
  
  ![Annotation 2020-06-09 224142](https://user-images.githubusercontent.com/57726348/84178749-92a60880-aaa2-11ea-9bb2-fb4fdde157ed.jpg)

2020-06-09 17:16 UTC, tirthajyoti-ghosh reviewed
[OPTIONAL] Decrease the font size of `section.hero h1`.

*Since you are using Github actions, you can disable stickler on this project.*

Apply these changes and request for another code review.

Happy coding 👨‍💻

2020-06-10 12:35 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @Abidoyinsola1 and @somoye123     :handshake: 

### Good job so far :clap:  your project looks like the original :medal_sports: 

### there are some changes to get the project approved :point_down: , please check the comments and once you are done with the requirements ask for another code review.

2020-06-10 12:35 UTC, HADDADSOHAIB commented on index.html
> +            <hr style="margin: 50px 0 0;" />
Please remove inline styles

2020-06-10 12:35 UTC, HADDADSOHAIB commented on index.html
> +            <hr style="margin: 50px 0 0;" />
Please remove inline styles

2020-06-10 12:35 UTC, HADDADSOHAIB commented on index.html
> +    </nav>
As requested by the previous TSE, the nav shrinks when you reduce the height, please fix that.

2020-06-10 12:35 UTC, HADDADSOHAIB commented on index.html
> +              </ul>
These icons should be links, add href="#" so they will look as link (the cursor will have a pointer)

2020-06-10 12:35 UTC, HADDADSOHAIB commented on index.html
> +          </div>
All these articles (the articles with images in the footer) should be links:
![Screenshot from 2020-06-10 13-32-44](https://user-images.githubusercontent.com/26064042/84268002-e3f3dd80-ab1e-11ea-9561-5f95db349e3d.png)

2020-06-10 12:51 UTC, Abidoyinsola1 commented on index.html
> +    </nav>
Hello @haddadsohaib can you explain more on what you mean by the reduced height? A screenshot would help in clarifying. Thank you.

2020-06-10 13:47 UTC, Abidoyinsola1 commented
All necessary corrections have been made, but more explanation is needed on the issue raised concerning the navigation bar.

2020-06-10 13:54 UTC, HADDADSOHAIB commented
- Check the differences between these two:
- Original article:
![Screenshot from 2020-06-10 14-51-15](https://user-images.githubusercontent.com/26064042/84276234-02130b00-ab2a-11ea-9c8e-1f4699a2cc65.png)
- Your project:
![Screenshot from 2020-06-10 14-51-33](https://user-images.githubusercontent.com/26064042/84276260-09d2af80-ab2a-11ea-949d-fe3801b86041.png)
When the height of the page is reduced, the nav become smaller and the logo, buttons don't fit any more, in the original article the nav height is a fixed value

2020-06-10 13:56 UTC, HADDADSOHAIB commented on index.html
> +    </nav>
@Abidoyinsola1  hi, check my comment down I added some screenshots

2020-06-10 14:52 UTC, somoye123 commented
Nav shrinking issues when the height is reduced as been fixed

2020-06-10 18:08 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-10 18:14 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, you guys did a great job fixing all the comments pointed out by the previous TSE's :+1: Thanks to your persistent desire to improve and the guidance of our TSE's :slightly_smiling_face: Our project now meets all the minimum requirements :hugs: 

You can now merge to master and submit the project completion form
Good luck with your next projects :100: 
_Happy coding_ :woman_technologist: :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-11 07:42 UTC, merged